/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 09-Mar-2015 05:27:48
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/*
 * Expected path to tmwtypes.h
 * /Applications/MATLAB_R2014a.app/extern/include/tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BLUE_LOW_NL = 5;
const float BLUE_LOW_NUM[5] = {
    0.09731980413,  -0.3164561987,   0.4471443892,  -0.3164561987,  0.09731980413
};
const int BLUE_LOW_DL = 5;
const float BLUE_LOW_DEN[5] = {
                1,   -3.267053843,    4.538989067,   -3.062070131,   0.8788509369
};
