/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
 * Generated on: 09-Mar-2015 15:14:04
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Numerator Length    : 6
 * Denominator Length  : 6
 * Stable              : Yes
 * Linear Phase        : No
 */

/*
 * Expected path to tmwtypes.h
 * C:\Program Files\MATLAB\R2014b\extern\include\tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int RED_LOW_NL = 6;
const float RED_LOW_NUM[6] = {
   0.008617528714, -0.02513361722,  0.01653003693,  0.01653003693, -0.02513361722,
   0.008617528714
};
const int RED_LOW_DL = 6;
const float RED_LOW_DEN[6] = {
                1,    -4.81879425,     9.32675457,    -9.06200695,    4.419505119,
    -0.8654303551
};
