/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 09-Mar-2015 05:40:45
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/*
 * Expected path to tmwtypes.h
 * /Applications/MATLAB_R2014a.app/extern/include/tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int YELLOW_NL = 5;
const float YELLOW_NUM[5] = {
    0.09731980413, -0.09320958704,   0.2026493996, -0.09320958704,  0.09731980413
};
const int YELLOW_DL = 5;
const float YELLOW_DEN[5] = {
                1,  -0.9622839689,    2.094039202,   -0.901907742,   0.8788509369
};
