/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 09-Mar-2015 05:34:12
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/*
 * Expected path to tmwtypes.h
 * /Applications/MATLAB_R2014a.app/extern/include/tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BLUE_HIGH_NL = 7;
const float BLUE_HIGH_NUM[7] = {
    0.01907765307,  0.04380258918,  0.04380568489,              0, -0.04380568489,
   -0.04380258918, -0.01907765307
};
const int BLUE_HIGH_DL = 7;
const float BLUE_HIGH_DEN[7] = {
                1,     3.39504981,    6.713463306,    7.959328651,    6.447431564,
      3.130913973,   0.8855849504
};
