/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 09-Mar-2015 05:39:38
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Numerator Length    : 7
 * Denominator Length  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/*
 * Expected path to tmwtypes.h
 * /Applications/MATLAB_R2014a.app/extern/include/tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int RED_NL = 7;
const float RED_NUM[7] = {
    0.01168008801,  0.02220035717,  0.02212286741,              0, -0.02212286741,
   -0.02220035717, -0.01168008801
};
const int RED_DL = 7;
const float RED_DEN[7] = {
                1,    2.822654486,    5.579748154,    6.338991165,    5.445928574,
      2.688783169,   0.9297059178
};
